Repository hatchways/team-corgi, pull requests merged in 2021-06, with the labels that each got.

#41 Add model for Profile
  server/models/Profile.js
Labels: Backend

#43 Add routes/controllers for Profile
  server/controllers/profile.js
  server/routes/profile.js
Labels: Backend

#46 Add Protected Routes
  client/src/App.tsx
  client/src/components/ProtectedRoutes/ProtectedRoutes.tsx
Labels: Backend

#49 Feature add landingpage
  client/src/App.tsx
  client/src/helpers/APICalls/makeSitterRequest.ts
  client/src/pages/LandingPage/LandingPage.tsx
  client/src/pages/LandingPage/LandingPageForm/LandingPageForm.tsx
  client/src/pages/LandingPage/LandingPageForm/useStyles.ts
  client/src/pages/LandingPage/useStyles.ts
Labels: Frontend

#47 added Requests model
  server/models/Requests.js
Labels: Backend

#53 Profile pic up
  client/src/components/AvatarDisplay/AvatarDisplay.tsx
  client/src/components/ProfilePhoto/ProfilePhoto.tsx
  client/src/components/ProfilePhoto/useStyles.ts
  server/controllers/profilePhoto.js
  server/routes/profilePhoto.js
Labels: Frontend

#52 add request controllers
  server/controllers/requests.js
  server/package-lock.json
  server/package.json
Labels: Backend

#48 Changed availability in Profile Modal
  server/models/Profile.js
Labels: Backend

#57 notification model
  client/package-lock.json
  client/package.json
  client/src/components/Notification/Notification.tsx
  client/src/interface/Notification.ts
  client/src/pages/Dashboard/Dashboard.tsx
  server/app.js
  server/controllers/notifications.js
  server/controllers/user.js
  server/models/Notifications.js
  server/models/Profile.js
  server/package.json
  server/routes/notifications.js
  server/routes/profile.js
  server/routes/user.js
Labels: Backend

#62 Profile pic upload backend
  client/package-lock.json
  client/package.json
  client/src/components/ProfilePhoto/ProfilePhoto.tsx
  client/src/components/Sidebar/SideBar.tsx
  client/src/helpers/APICalls/uploadPic.ts
  client/src/interface/FetchOptions.ts
  server/app.js
  server/controllers/profilePhoto.js
  server/models/Profile.js
  server/package-lock.json
  server/package.json
  server/routes/profilePhoto.js
  server/utils/cloudinary.js
Labels: Backend

#64 Edit profile
  client/src/App.tsx
  client/src/components/EditProfile/EditProfile.tsx
  client/src/components/EditProfile/useStyles.ts
  client/src/helpers/APICalls/editProfile.ts
  client/src/interface/AuthApiData.ts
  client/src/interface/Profile.ts
  server/routes/profile.js
Labels: Integration

#63 new dashboard commit
  client/src/components/DashboardCoponent/Content.tsx
  client/src/components/DashboardCoponent/DashboardComponent.jsx
  client/src/components/DashboardCoponent/Header.jsx
  client/src/components/DashboardCoponent/ProfileCard.tsx
  client/src/components/DashboardCoponent/logo.png
  client/src/pages/Dashboard/Dashboard.tsx
  server/package-lock.json
  server/package.json
Labels: Frontend
