Repository hatchways/team-corgi, pull requests merged in 2021-07, with the labels that each got.

#69 Manage bookings
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/CompareDay/CompareDay.ts
  client/src/components/ManageBookings/BookModule/CurrentBookings.tsx
  client/src/components/ManageBookings/BookModule/EachBooking/EachBooking.tsx
  client/src/components/ManageBookings/BookModule/EachBooking/useStyles.ts
  client/src/components/ManageBookings/BookModule/useStyles.ts
  client/src/components/ManageBookings/Calendar.css
  client/src/components/ManageBookings/ManageBookings.tsx
  client/src/components/ManageBookings/useStyles.ts
  client/src/interface/Request.ts
  client/src/pages/Dashboard/Dashboard.tsx
  server/models/Requests.js
Labels: Frontend

#73 Manage bookings UI
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/CompareDay/CompareDay.ts
  client/src/components/ManageBookings/BookModule/CurrentBookings.tsx
  client/src/components/ManageBookings/BookModule/EachBooking/EachBooking.tsx
  client/src/components/ManageBookings/BookModule/EachBooking/useStyles.ts
  client/src/components/ManageBookings/BookModule/useStyles.ts
  client/src/components/ManageBookings/Calendar.css
  client/src/components/ManageBookings/ManageBookings.tsx
  client/src/components/ManageBookings/useStyles.ts
  client/src/interface/Request.ts
  server/models/Requests.js
Labels: Frontend

#74 Add basic backend message functionality
  server/app.js
  server/controllers/conversations.js
  server/controllers/messages.js
  server/models/Conversation.js
  server/models/Messages.js
  server/routes/conversations.js
Labels: Backend

#75 Feature/socket setup
  client/package.json
  client/src/components/AuthMenu/AuthMenu.tsx
  client/src/components/DashboardCoponent/Header.jsx
  client/src/context/useAuthContext.tsx
  client/src/pages/Dashboard/Dashboard.tsx
  client/src/pages/Login/Login.tsx
  server/app.js
  server/controllers/profile.js
Labels: Fullstack
